### ISSUE TITLE
String constants are not converted to lua.

### ISSUE THREAD

**Issue by Wyzoom** [astrochili/narrator#1]
Hi 

Consider the following ink code : 

CONST a = 1
CONST b = "myString"
CONST c = "true"
CONST d = "false"
-> knot
== knot ==
Hello
a = {a}
b = {b}
c = {c}
d=  {d}
->END

As an ink file, it works fine, producing b = myString. When converted to lua, and pretty printed using the inspect.lua library produces the following output :
`
{
  constants = {
    a = 1,
    c = true,
    d = false
  },
  inclusions = {},
  lists = {},
  tree = {
     = {
       = { {
          divert = "knot"
        } }
    },
    knot = {
      _ = { "Hello", "a = #a#", "b = #b#", "c = #c#", "d= #d#", {
          divert = "END"
        } }
    }
  },
  variables = {},
  version = {
    engine = 1,
    tree = 1
  }
}
`
Please note that the constant b = "myString" is not present.

**Comment by astrochili** [comment]
@Wyzoom Hi! Fixed it :)

**Comment by Wyzoom** [comment]
Great, thank you for the super fast fix! We found another possible bug,  variables that are declared before the first know not being converted to the lua table. Will open a new issue in asap.

Cheers
Wyzoom
