### ISSUE TITLE
It is impossible to fetch the current paragraph

### ISSUE THREAD

**Issue by wistpotion** [astrochili/narrator#20]
### Description
The only way (I know of) to fetch a paragraph from Narrator is to use `story:continue`. When using `story:continue` the story steps forward and then returns the next paragraph, meaning that there is no way to fetch the paragraph that should currently be displayed 
to the user.  

This is a problem when loading data. Since it is impossible to get the paragraph that currently should be displayed, the story has to step forward one paragraph and then display that, which results in an odd experience for the player, as their savefile seems to jumped a step forward without them doing anything. 

Loading when at a choice works just as expected though. If the player saves at a choice, they load at a choice. 

### Workaround
Possible workarounds are keeping the save data from the previous step and save that if the current content is a paragraph. This does however not work if the previous content is a choice, as the player will load at the choice then. To solve that, one could also save the decision made at that choice and automatically answer it, to then load the next paragraph. Not very clean. 

### Proposed resolution
Currently there are two ways to fetch all the content up to the next choice: with `story:continue(nil)` and `story:continue(0)`. It would make more sense for `story:continue(0)` to return the current paragraph, and it would solve the problem.

**Comment by astrochili** [comment]
The call `story:continue()` returns the next paragraph, this is correct. If you start the story, it will return the first paragraph, then the second, then the third, etc.

Ink's paradigm is that `continue()` outputs paragraph after paragraph, and when the paragraphs end, gives you a list of options to choose from. In other words, there are only two states of the framework:

1) The framework has paragraphs that the game should get itself.
2) The framework has run out of paragraphs and now has options and is waiting to choose.

After `continue()` the story no longer stores outputted text, this is the responsibility of the host game to keep the resulting paragraphs that the story produces. The framework is a more low-level solution. As far as I know, the official C# APIs for Unity and JS for the web have a similar interface.

The easiest solution is to save the output to your local variable, either in paragraphs or solid text, as desired. This allowed you to work with paragraphs further as you want.

When I implemented my game, I made my own variable where I put the paragraphs output from the story and saved them along with saving the game. When the game is loaded, it displays this "already printed text" and prompt the player to "continue". There is no need to call `continue()` immediately after loading the game if we want to restore the player's saved state. Can this solution help you?
