### ISSUE TITLE
VARS declared before first knot not listed under global variables table entry

### ISSUE THREAD

**Issue by Wyzoom** [astrochili/narrator#3]
Input ink file: 

VAR a = "foo"
VAR b = "bar"
CONST c = 42
CONST d = "Number 42"

-> first_knot

== first_knot ==

In the knot a = {a}
In the knot b = {b}

-> second_knot 

== second_knot ==
Then we change them :
~ a = "baz"
~ b = "bazbar"

Now a = {a}
and b = {b}

->DONE

Convert to lua using narrator 1.2 produces :

return {variables={},lists={},inclusions={},constants={d="Number 42",c=42},version={tree=1,engine=1},tree={first_knot={_={"In the knovt a = #a#","In the knot b = #b#",{divert="second_knot"},""}},second_knot={_={"Then we change them :",{value="\"baz\"",var="a"},{value="\"bazbar\"",var="b"},"Now a = #a#","and b = #b#",{divert="DONE"}}},_={_={{value="\"foo\"",var="a"},{value="\"bar\"",var="b"},{divert="first_knot"}}}}}

We see at the beginnig of the output : 
As expected : constants={d="Number 42",c=42} 
Not expected : variables={}

We only see variables a and b being outputted as variable definitions  within the second knot, en their value is set the second time. They are present at the end of the output, but not at a place we would expect them.

Greetings, and thanks for writing narrator!
Wyzoom

**Comment by astrochili** [comment]
@Wyzoom Thanks for the feedback!

The problem was that variables were assigned at runtime. Improved it in [1.3](https://github.com/astrochili/narrator/releases/tag/1.3), now variables are assigned after parsing.
